name: CI

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    env:
      MY_ASTRO_DATA: ${{ github.workspace }}/my_astro_data/
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"
      - name: Install dependencies
        run: |
          python -m pip install numpy astropy astroquery h5py pandas tqdm wheel pytest sklearn torch gaiadr3-zeropoint MyGaiaDB GaiaXPy 
      - name: Test
        run: |
          python -m pytest -v -s tests/